name: Publish

on:
  push:
    branches:
      - master
    paths:
      - 'assets/application.json'
      - 'ecomplus-market.json'
      - 'description.md'
      - 'scripts/market-publication.js'

jobs:
  pulish:
    name: Publish app to E-Com Plus Market
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm i

      - name: Run publish script
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          MARKET_TOKEN: ${{ secrets.MARKET_TOKEN }}
        run: "npm run publish:market"
